TARGET_ARCH=x86 arm
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := sqlite3
LOCAL_CFLAGS    := -Werror -DSQLITE_HAS_CODEC -DSQLITE_ENABLE_EXTFUNC -DHAVE_ACOSH -DHAVE_ASINH -DHAVE_ATANH -DHAVE_ISBLANK
LOCAL_SRC_FILES := sqlite3secure.c

include $(BUILD_SHARED_LIBRARY)
